sudo: required
language: python
matrix:
    include:
        - python: 3.6
          dist: trusty
          env: TOXENV=py36
          addons:
              postgresql: "9.5"
install:
    - pip install tox
script:
    - tox
